"""empty message

Revision ID: 4b82c3716667
Revises: 02b4dab83e75
Create Date: 2024-06-25 09:37:17.011497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b82c3716667'
down_revision = '02b4dab83e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('job_number', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=40), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('job_number')
        batch_op.drop_column('position')

    # ### end Alembic commands ###
