"""empty message

Revision ID: 683a37d4e00c
Revises: 435b024c1ef6
Create Date: 2023-12-29 16:37:55.467093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683a37d4e00c'
down_revision = '435b024c1ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_img',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.Column('use_context', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_img')
    # ### end Alembic commands ###
