"""empty message

Revision ID: 790b40145372
Revises: 673d8eb0d488
Create Date: 2024-06-20 15:29:59.444219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790b40145372'
down_revision = '673d8eb0d488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_items', schema=None) as batch_op:
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
