"""empty message

Revision ID: e4671785cac0
Revises: ed7898d85c51
Create Date: 2023-12-29 16:41:37.413971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4671785cac0'
down_revision = 'ed7898d85c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_img', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.drop_column('URL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_img', schema=None) as batch_op:
        batch_op.add_column(sa.Column('URL', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
