"""empty message

Revision ID: ed7898d85c51
Revises: 683a37d4e00c
Create Date: 2023-12-29 16:40:16.656919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed7898d85c51'
down_revision = '683a37d4e00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_img', schema=None) as batch_op:
        batch_op.add_column(sa.Column('URL', sa.String(length=100), nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('use_context')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_img', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_context', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('URL')

    # ### end Alembic commands ###
